### ISSUE TITLE
Evaluate state of account signing propagation

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#10]
- [x] @ripcurlx to see how effective the change has been
 - [x] @ripcurlx to create issue in growth repo to track this at a high level / write up plan / tasks, etc.

Per decision made in #1
Part of bisq-network/projects#10

**Comment by cbeams** [comment]
Note that this work is important because if our suspicions about account signing propagation (or lack thereof) are true, there are not enough signed accounts in many markets, and this will impede our liquidity goals.

**Comment by ripcurlx** [comment]
I started to gather some data over the API and from within our client in following spreadsheets.

Important points of time:
- **May 6th**: Limit of 0.01 BTC was introduced with version v1.1.1
- **Nov 1st**: Account Signing was launched in version v1.2.2

As we don't have historical data I looked at our current offerbook on how many offers are offers with a signed account and how many offer maker have a signed account.

I also looked at the signed witness store over time. We don't have payment account or currency specific information so we can only check the general total growth:
![Signed accounts over time](https://user-images.githubusercontent.com/170962/74826048-3b213880-530b-11ea-9171-8cfff30b5190.png)
![Signed accounts over time (log)](https://user-images.githubusercontent.com/170962/74826052-3c526580-530b-11ea-9625-a1c5ff7a3a8f.png)

New signed accounts/Day (Median) | New signed accounts/Day (Average) | Growth/Day (median) | Growth/Day (avg)
-- | -- | -- | --
7 | 17.27826087 | 0.35% | 0.87%

## USD - ZELLE
https://docs.google.com/spreadsheets/d/1g2-WoYm_wumttfAA8z_1dDxG8Qx5_JDsHrKmv0jNJ5s/edit?usp=sharing

### Offer book (Feb 19th 2020)
![Number of Offers (1)](https://user-images.githubusercontent.com/170962/74819935-73bc1480-5301-11ea-8caf-1d9c8600eace.png)
![Offers with signed and unsigned account (1)](https://user-images.githubusercontent.com/170962/74819938-74ed4180-5301-11ea-8b23-7d79c54d1025.png)
![Signed maker and unsigned maker (1)](https://user-images.githubusercontent.com/170962/74819936-7454ab00-5301-11ea-933b-e69ed7a17ec2.png)
![Number of Offers (3)](https://user-images.githubusercontent.com/170962/74827486-d61b1200-530d-11ea-93ed-841c3b54daee.png)

### Trades
![Percentage of trades _ 0 01BTC vs total trade volume (1)](https://user-images.githubusercontent.com/170962/74816281-19b85080-52fb-11ea-8de2-224bc48d84d5.png)
![Avg  trade size vs Number of trades (1)](https://user-images.githubusercontent.com/170962/74816283-1a50e700-52fb-11ea-9b80-7a3118880201.png)

## EUR - SEPA
https://docs.google.com/spreadsheets/d/1GwuaxMOsl4tDWbMhzpO_zdORaDKCztpUA2e8aPkPPCg/edit?usp=sharing

### Offer book (Feb 19th 2020)
![Number of Offers](https://user-images.githubusercontent.com/170962/74819199-4fac0380-5300-11ea-9772-017a0f9e6739.png)
![Offers with signed and unsigned account](https://user-images.githubusercontent.com/170962/74819194-4e7ad680-5300-11ea-96de-fc6909c247b4.png)
![Signed maker and unsigned maker](https://user-images.githubusercontent.com/170962/74819197-4f136d00-5300-11ea-964c-b8e3d586f037.png)
![Number of Offers (4)](https://user-images.githubusercontent.com/170962/74827526-e29f6a80-530d-11ea-8337-4212e2bec355.png)

### Trades
![Percentage of trades _ 0 01BTC vs total trade volume](https://user-images.githubusercontent.com/170962/74816285-1ae97d80-52fb-11ea-8c80-b29a074ce839.png)
![Avg  trade size vs Number of trades](https://user-images.githubusercontent.com/170962/74816287-1b821400-52fb-11ea-98fa-f0505717dc20.png)

## BRL - National banks
https://docs.google.com/spreadsheets/d/1jkAscuX40PNpQMOJwl2ULkEMtu4ashfoXuTC5t6hSCg/edit?usp=sharing

### Offer book (Feb 19th 2020)
![Number of Offers (6)](https://user-images.githubusercontent.com/170962/74829515-7c1c4b80-5311-11ea-8ff4-24814c77acc6.png)
![Signed maker and unsigned maker (2)](https://user-images.githubusercontent.com/170962/74829518-7d4d7880-5311-11ea-92f9-067abb94fb2b.png)
![Offers with signed and unsigned account (2)](https://user-images.githubusercontent.com/170962/74829519-7d4d7880-5311-11ea-9caa-ab908b91762f.png)
![Number of Offers (5)](https://user-images.githubusercontent.com/170962/74829522-7de60f00-5311-11ea-8c3d-bf57990680f7.png)

### Trades
![Percentage of trades _ 0 01BTC vs total trade volume (4)](https://user-images.githubusercontent.com/170962/74829572-99511a00-5311-11ea-92ee-35a13db268dd.png)
![Avg  trade size vs Number of trades (4)](https://user-images.githubusercontent.com/170962/74829574-99e9b080-5311-11ea-898f-4562b39023a2.png)


## CAD - Interac-E-Transfer

![Percentage of trades _ 0 01BTC vs total trade volume (3)](https://user-images.githubusercontent.com/170962/74828318-33fc2980-530f-11ea-94a7-8703d2013f5d.png)
![Avg  trade size vs Number of trades (3)](https://user-images.githubusercontent.com/170962/74828321-352d5680-530f-11ea-93c4-2c9e84186bf8.png)


## Conclusion

We did make a turn in Nov '19 to stop the liquidity downwards spiral. But neither market where we introduced account signing has fully recovered yet. Not in total volume or in average trade size. (~65+% should be a target to reach for trades above our 0.01 BTC limit). Growth of signed accounts is also quite static right now.

### Major markets (USD, EUR)
There is an obvious difference in the USD and EUR market. The USD market seems to have a good saturation of signed accounts (at least in the available offers) and it is also focusing on trades for new traders that are below the initial limit. The EUR market in contrast could be improved by a higher percentage of signed accounts and more offers for unsigned users.  So in general it doesn't look like for those two markets as if we have a big problem in the account signing seeding. There might be still ways to improve that (will be discussed in action points of project), but I have the feeling that it might be more a communication problem than a signed account seeding problem for those markets.

### CAD
This market is so small it is hard to make proper assumptions (4 offers in total atm). We do have signed accounts in this market, but I guess we need more feedback from users if something else is needed for improvement

### GBP
In this market mainly `Faster Payments` is used that has no account signing activated. Not sure if account signing for other payment methods is a real showstopper right now.

### BRL
This market just has been started to grow over the last couple of months and it seems there are not too little signed accounts available already. So I don't think we need to do something special for this market, that wouldn't be covered by tasks for the major markets.

### AUD
This market is also so small atm that it is hard to make any assumptions (2 offers).

 I'll prepare next an issue/project with action points on how to improve the account signing state.

**Comment by cbeams** [comment]
Great work, @ripcurlx! The numbers do look quite good on the USD side. Note that I created a project issue for this a couple days ago at bisq-network/projects#10, and I've just updated it to reflect that this evaluation task is complete. Could you keep that up to date with further tasks, etc?

And I'd say go ahead and close this specific task issue now that we have the numbers from the evaluation. Unless for some reason you wish to keep it open.

**Comment by ripcurlx** [comment]
> Note that I created a project issue for this a couple days ago at [bisq-network/projects#10](https://github.com/bisq-network/projects/issues/10), and I've just updated it to reflect that this evaluation task is complete. Could you keep that up to date with further tasks, etc?

Will do. Looking right now at the current state of the signing flow again to have a better picture what can be improved and at strategies to increase signed accounts.
