### ISSUE TITLE
Scope and decide on USDT integration

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#11]
- [ ] @ripcurlx to scope work / figure out which implementation(s) to use 
- [ ] @m52go to decide whether it’s something we really want / are going to push in v1.2.6

Per decision made in #1

**Comment by ripcurlx** [comment]
I would put this task on hold for now until we see if the addition of L-BTC helped us to improve liquidity. There is more high prio stuff right now IMO than pushing for proper integration of USDT.

**Comment by cbeams** [comment]
Agreed, @ripcurlx. Closing as dropped.
