### ISSUE TITLE
Follow up re Transifex Admin role changes

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#15]
Per decision made in #1

**Comment by m52go** [comment]
I reached out last Thursday (the day of the call in which this issue was raised), followed up on Monday, and still haven't heard back.

**Comment by cbeams** [comment]
On the agenda for #29.

**Comment by m52go** [comment]
@MwithM was assigned as Transifex Admin, and the [hand-off was done in Cycle 11](https://github.com/bisq-network/roles/issues/20#issuecomment-592415120).
