### ISSUE TITLE
Write initial dev team announcement

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/admin#17]

**Comment by cbeams** [comment]
Thanks for adding this, @ripcurlx. Please assign yourself or whomever else is appropriate when you create these issues (I already assigned you just now).

Feel free to post a draft of the announcement as a comment if you want any kind of review from me. Not at all required, please feel free to just send it as well, but thought I'd mention.

**Comment by cbeams** [comment]
@ripcurlx, I believe this is complete with the publication of https://github.com/orgs/bisq-network/teams/dev/discussions/1. Please close this issue if so, thanks.
