### ISSUE TITLE
Enable wiki email notifications

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#18]
Currently, the only way to know that something you care about on the wiki has changed is to go to the https://bisq.wiki/Special:Watchlist page. This will show you recent changes to only those pages that are on your watchlist. Pages you create, and I believe pages that you've edited are automatically added to your watchlist.

This is a pull system and we need a push system. Something that will send out notifications via email anytime an article on your watchlist has changed. Ideally, something that gives the option to get notifications any time _any_ article changes. The latter is good for those playing a more global "editor" role, or for anyone who just wants to keep up to date with everything that's going on in the wiki.

I've searched very briefly and I see that there are ways to enable notifications, but I have not looked at any of them more than just a glance.

Can someone figure this out, and ultimately have @wiz implement it on the wiki? The utility of the wiki is greatly diminished, and the likelihood that anyone will really help edit others' work is pretty low if we don't get some sort of notifications in place. Also, we could currently go a long time not knowing it if someone started adding garbage content to the wiki, or otherwise vandalizing existing content.

**Comment by wiz** [comment]
Done. Here's how you do it:

1) Press this button to request confirming your email address https://bisq.wiki/Special:ConfirmEmail
<img width="618" alt="Screen Shot 2020-02-11 at 11 03 45" src="https://user-images.githubusercontent.com/232186/74206577-55319a00-4cbf-11ea-94d6-8dfdec8f8d8b.png">

2) You should get an email with a link in it
<img width="228" alt="Screen Shot 2020-02-11 at 11 04 31" src="https://user-images.githubusercontent.com/232186/74206630-8d38dd00-4cbf-11ea-9b05-ee3555c552ea.png">

3) Click the link and confirm your email
<img width="328" alt="Screen Shot 2020-02-11 at 11 04 10" src="https://user-images.githubusercontent.com/232186/74206586-611d5c00-4cbf-11ea-97c9-0a9e4d1d3036.png">

4) Then you can enable these settings https://bisq.wiki/Special:Preferences#mw-prefsection-personal
<img width="443" alt="Screen Shot 2020-02-11 at 11 08 15" src="https://user-images.githubusercontent.com/232186/74206452-e5bbaa80-4cbe-11ea-9c18-be6b854c1e54.png">

5) Manage your watchlist https://bisq.wiki/Special:Preferences#mw-prefsection-watchlist
<img width="659" alt="Screen Shot 2020-02-11 at 11 06 39" src="https://user-images.githubusercontent.com/232186/74206539-359a7180-4cbf-11ea-9ed2-c467776744b1.png">

**Comment by m52go** [comment]
Late...but would like to point out that there's an Atom feed for anyone looking to track changes across the wiki. I've been using it with a feed reader with notifications turned on, and it works great.

https://bisq.wiki/api.php?hidebots=1&urlversion=1&days=7&limit=50&action=feedrecentchanges&feedformat=atom

**Comment by cbeams** [comment]
Excellent! Thank you for pointing this out, I wasn't aware. For greater ease, people can just add https://bisq.wiki/Special:RecentChanges to their feed reader and the atom link above will (should) be auto-discovered.
