### ISSUE TITLE
Publish blog post on reorg

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#21]
@m52go's draft, per Keybase chat

> keybase://private/m52go%2Ccbeams/2020-02-01-bisq-q1-2020-update.md

It is a recap of the content laid out in the Q1 2020 Update call at #5.

**Comment by cbeams** [comment]
@m52go, I just read through this quickly and it looks great. Please go ahead with fleshing it out and publishing. Thanks.

**Comment by m52go** [comment]
@cbeams full draft is complete and on our Keybase shared folder for you to review.

**Comment by cbeams** [comment]
I've added my notes in our chat, thanks.
