### ISSUE TITLE
Add TXT DNS record for bisq.wiki email

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#24]
@wiz wrote via chat:

> the bisq wiki server needs to be able to send email from `@bisq.wiki` - can you add the following DNS record
> ```
> bisq.wiki. IN TXT "v=spf1 a -all"
> mail._domainkey.bisq.wiki. IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4TR6OhKEKroxplWStyTFQKxrMIeedS4XqQNCvXMMbsPmXFeHlLmkHPUDJbs7Xt+nRw4uLB7KtPuCCgELOMVZyt0ZjPKXLGq2I6lSUuz/ZCNEHp78yODZfD7LbTmHAZ264zlXnf66Jyzdc3K5m7jv1buy8Tn474rvHi3vKKqKefgS8VeYFaMyfWJ+jwgC2J3ZaodrezvZug7zawqArPveI8hUnanVI18draouZ5cMILCqELhjq3zLeCga/K8F+xV/+pHJH/hqRENxV1c22V9ZMZVbUVnktZyj2FtNTBnnnRsmHC9zHBz+deZMnOQmgDaOyfO0EThL0ls0D/HpUHIEQIDAQAB"
> ```
>
> 
> I've enabled it now but without this the emails might go into people's "spam" folders
> the first one will whitelist the "a" record to send email for the domain, the second adds a public key that the outgoing mail can be cryptographically signed with, so users mailboxes can verify it was "signed by bisq.wiki"

Part of #18

**Comment by cbeams** [comment]
@wiz, I'm getting the following error when trying to add this record:

```
TXT records parts can't be longer than 255 chars
```

The record you posted above is 410 chars. Please advise.

**Comment by wiz** [comment]
Yeah DKIM records are tricky because you need to break it up into multiple DNS records, and this can vary depending on where you host the DNS. For example in BIND9 you would do something like this using paranthesis and then it combines them internally somehow. I suggest contacting your DNS hosting provider's help desk or maybe they have a FAQ on how to set a DKIM record, or if not maybe just set the DNS servers for the wiki domain to my DNS servers and I can host DNS for that.
 
```
bisq.wiki. IN TXT "v=spf1 a -all"
bisq.wiki.dkim._domainkey	IN	TXT	( "v=DKIM1; k=rsa; "
"p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4TR6OhKEKroxplWStyTFQKxrMIeedS4XqQNCvXMMbsPmXFeHlLmkHPUDJbs7Xt+nRw4uLB7KtPuCCgELOMVZyt0ZjPKXLGq2I6lSUuz/ZCNEHp78yODZfD7LbTmHAZ264zlXnf66Jyzdc3K5m7jv1buy8Tn474rvHi3vKKqKefgS8VeYFaMyfWJ+jwgC2J3ZaodrezvZug7za"
"wqArPveI8hUnanVI18draouZ5cMILCqELhjq3zLeCga/K8F+xV/+pHJH/hqRENxV1c22V9ZMZVbUVnktZyj2FtNTBnnnRsmHC9zHBz+deZMnOQmgDaOyfO0EThL0ls0D/HpUHIEQIDAQAB" )
```

**Comment by wiz** [comment]
I setup `bisq.wiki` on my DNS servers, feel free to change DNS to `dns01.wiz.biz` and `dns02.wiz.biz`

**Comment by cbeams** [comment]
Thanks, @wiz. I've added the broken up TXT entries as you posted them above.

Please test this configuration to make sure the entries are doing what they need re avoiding spam filters and close this issue out with any comments.

**Comment by cbeams** [comment]
> feel free to change DNS to `dns01.wiz.biz` and `dns02.wiz.biz`

**Comment by cbeams** [comment]
Reopening as accidentally closed. @wiz, please see my last comment.

**Comment by wiz** [comment]
It doesn't seem to work, `host -t txt dkim._domainkey.bisq.wiki` should return the pubkey. But if your hosting provider doesn't support it, don't worry, DKIM is optional and not required for our use case, I'm simply following best practices.

**Comment by wiz** [comment]
For example here's a DKIM checker utility you can use. In our case selector is "dkim" or "mail" in the 2 records above, either is fine https://mxtoolbox.com/SuperTool.aspx?action=dkim%3awiz.biz%3agoogle&run=toolpage

**Comment by cbeams** [comment]
@wiz wrote:
> It doesn't seem to work, `host -t txt dkim._domainkey.bisq.wiki` should return the pubkey.

This was my bad. I mis-entered the TXT entry. It works now (though hasn't propagated yet, waiting on 10800ms TTL):

```
$ host -t txt dkim._domainkey.bisq.wiki ns-148-a.gandi.net
Using domain server:
Name: ns-148-a.gandi.net
Address: 173.246.100.149#53
Aliases:

dkim._domainkey.bisq.wiki descriptive text "v=DKIM1; k=rsa; " "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4TR6OhKEKroxplWStyTFQKxrMIeedS4XqQNCvXMMbsPmXFeHlLmkHPUDJbs7Xt+nRw4uLB7KtPuCCgELOMVZyt0ZjPKXLGq2I6lSUuz/ZCNEHp78yODZfD7LbTmHAZ264zlXnf66Jyzdc3K5m7jv1buy8Tn474rvHi3vKKqKefgS8VeYFaMyfWJ+jwgC2J3ZaodrezvZug7za" "wqArPveI8hUnanVI18draouZ5cMILCqELhjq3zLeCga/K8F+xV/+pHJH/hqRENxV1c22V9ZMZVbUVnktZyj2FtNTBnnnRsmHC9zHBz+deZMnOQmgDaOyfO0EThL0ls0D/HpUHIEQIDAQAB"
```

@wiz, please close this if everything looks OK to you.

**Comment by wiz** [comment]
<img width="760" alt="Screen Shot 2020-02-13 at 20 45 55" src="https://user-images.githubusercontent.com/232186/74431235-dc3e6800-4ea1-11ea-944f-e2baffac2ec5.png">
