### ISSUE TITLE
Enable wiki image uploads

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#25]
@Bayernatoor wrote via chat:

> im trying to work on a wiki page, however, I don't seem to have any way of uploading pictures. Is this an option that must be enabled by the wiki creator?

See:

 - https://www.mediawiki.org/wiki/Help:Images
 - https://www.mediawiki.org/wiki/Help:Managing_files
 - https://www.mediawiki.org/wiki/Manual:Configuring_file_uploads

**Comment by wiz** [comment]
This is done, tested https://bisq.wiki/User:Wiz
In edit toolbar click image icon -> upload -> select a file (or drag and drop) -> check the box -> upload
