### ISSUE TITLE
Write mediator role documentation

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#26]
For bisq-network/roles#83.

Include:
 - Duties:
   - [ ] Respond to time of 48 hours or less

Per @leo816, mediator @bisquser has committed "in general" to responding within 48 hours, so this must become our published maximum response time. Of course faster is better. Within 24 hours is the goal, but that is not something achievable with the current mediation staff.

**Comment by cbeams** [comment]
@leo816, would you please follow the instructions at https://bisq.wiki/Role#Documentation to create a new wiki article at https://bisq.wiki/Mediator that documents the Mediator role? Browse other entries in the Roles category on the wiki for examples. Assuming you're up for that, I've assigned this issue to you. Thanks.

**Comment by leo816** [comment]
done

**Comment by cbeams** [comment]
Closing as complete, although I notice that the Mediator role doesn't actually contain the 48 hour response time SLA; the Mediation article does, but makes it sound like a requirement on the trader's side, not the mediator's.
