### ISSUE TITLE
Enable wiki editor extension

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#27]
Per request by @Bayernatoor (and in general something I've figured we'll want as well), please install and configure as appropriate the WikiEditor extension. See https://www.mediawiki.org/wiki/Extension:WikiEditor.

**Comment by wiz** [comment]
Done

<img width="565" alt="Screen Shot 2020-02-11 at 11 01 19" src="https://user-images.githubusercontent.com/232186/74206248-e738a300-4cbd-11ea-8440-30644274c16f.png">

**Comment by cbeams** [comment]
Thanks, @wiz. I've just confirmed this works on my side as well.
