### ISSUE TITLE
Document compensation review process in wiki

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#32]
This issue is part of https://github.com/bisq-network/projects/issues/7.

@MwithM, I've created an article at https://bisq.wiki/Compensation in order to capture the new compensation review process laid out at the link above —and eventually to fully replace the current documentation at https://docs.bisq.network/compensation.html. I've gotten the ball rolling in the new article by putting together an outline of the whole compensation request process, broken down by roles. In your role as a compensation maintainer, would you please complete transcribing the process laid out in https://github.com/bisq-network/projects/issues/7 into the new wiki article?

It is NOT necessary to completely transcribe and replace the current documentation at https://docs.bisq.network/compensation.html. You'll see where I've simply linked to relevant sections there for now, so as to make completing this task as simple as possible.

Thanks, and please let me know as questions arise.

**Comment by MwithM** [comment]
The process has been documented at the wiki, I hope it's fine. More info in this post:
https://github.com/bisq-network/projects/issues/7#issuecomment-587412178

**Comment by cbeams** [comment]
> The process has been documented at the wiki, I hope it's fine.

Thanks, @MwithM! Could you please also transcribe the Team Leads section. It's written up in the description of bisq-network/projects#7; just needs to be carried over and edited as appropriate.

**Comment by MwithM** [comment]
> Could you please also transcribe the Team Leads section.

Done, almost no edit needed.

**Comment by cbeams** [comment]
Closing as complete. See https://bisq.wiki/Compensation.
