### ISSUE TITLE
Add critical bugs to project board

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/admin#33]
- [x] label issues with `is:priority`
- [x] add issues to project board
- [x] label issues with `is:critical bug` where appropriate
- [x] add remaining critical bugs from support team

**Comment by cbeams** [comment]
>     * label issues with `is:priority`

@ripcurlx, thanks for adding this issue. Regarding labeling, I'd prefer that we create a new `is:critical bug`, or `is:critical` in conjunction with the existing `is:bug` label. `is:priority` is fine, too, but it's implied by `is:critical bug`. The `is:critical bug` label will allow us to automate via GitHub Actions adding this to the Critical Bugs board. `is:priority` alone will not.

Note that I've also updated the description of bisq-network/projects#16 to reference this task in the task list.

**Comment by ripcurlx** [comment]
I'll update those priority issues that are critical bugs. I'll still use `is:priority` as well as there are issues that are within our priorities, but not a bug per se.

**Comment by ripcurlx** [comment]
Done

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/projects#16 for remaining tasks related to establishing the Critical Bugs board and process. Thanks @ripcurlx and @leo816!

@ripcurlx, I noticed that the `In Progress` issues on the board do not have assignees. This by definition should never be the case. Can you assign the issues as appropriate?

**Comment by cbeams** [comment]
@cbeams wrote:

> [@ripcurlx] Can you assign the (`In progress`) issues as appropriate?

All good, I assigned them to @dmos62, as he is obviously the one working on them / submitting PRs for them.
