### ISSUE TITLE
Update project issues on master project board

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/admin#35]
https://github.com/orgs/bisq-network/projects/3

Update issues:
- [x] https://github.com/bisq-network/projects/issues/16
- [x] https://github.com/bisq-network/projects/issues/13
- [ ] https://github.com/bisq-network/projects/issues/10

**Comment by cbeams** [comment]
Closing as (mostly) complete, an no longer useful / relevant in any case. The only remaining checkbox was bisq-network/projects#10, and I've added a comment there asking @ripcurlx for an update.
