### ISSUE TITLE
Write Bisq Maintainer role documentation

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#39]
Part of bisq-network/projects#9 and bisq-network/projects#16.

- [x] @cbeams to add https://bisq.wiki/Bisq_Maintainer
- [x] @cbeams to link to https://bisq.wiki/Bisq_Maintainer from https://bisq.wiki/Dev_Team
- [x] @cbeams to update https://github.com/bisq-network/roles/issues/63 description
- [x] @bisq-network/bisq-maintainers to review https://bisq.wiki/Bisq_Maintainer
  - [x] @ripcurlx 
  - [x] @sqrrm

**Comment by cbeams** [comment]
My tasks above are complete. @bisq-network/bisq-maintainers, please review the doc, add a watch on it and indicate here that you've done so and I'll close this out. Thanks.

**Comment by ripcurlx** [comment]
ACK from my side. Only made a changed link suggestion.

**Comment by cbeams** [comment]
@sqrrm can you ACK that you've reviewed this new doc and are good with its contents? See the checkbox in the description. Thanks.

**Comment by sqrrm** [comment]
ACK

**Comment by cbeams** [comment]
Closing as complete.
