### ISSUE TITLE
Close all Cycle 10 compensation requests when vote reveal is complete

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#40]
Adding this tracking issue just to make sure this happens per process the first time around. No need for such issues in the future as it's all part of the documented process at https://bisq.wiki/Compensation.

@bisq-network/compensation-maintainers to
 - [x] Wait for vote reveal phase compeletion
 - [x] Label all compensation request issues as `was:approved` or `was:rejected`
 - [x] Close with appropriate comment

**Comment by MwithM** [comment]
I think that this is complete, just a little thing is missing: I'm not sure where to announce when contributors should send their requests.
Once I put a label on an issue as "accepted" or "rejected", a message is created. Is it really necessary to comment on the issue announcing that the issue `was accepted` or `was rejected`? If this step (comment and close an issue) is removed, I can label and close the issues straight from the Compensation board. This should be faster and easier.

**Comment by cbeams** [comment]
> I think that this is complete, just a little thing is missing: I'm not sure where to announce when contributors should send their requests.

You should send a message to `@bisq-network/dao` per the documentation at https://bisq.wiki/Compensation#Announce_request_submission_deadline.

> Once I put a label on an issue as "accepted" or "rejected", a message is created. Is it really necessary to comment on the issue announcing that the issue `was accepted` or `was rejected`?

If by "message" you mean "GitHub notification", this is incorrect. Labeling an issue does not create a notification, meaning that the people involved with that compensation request issue will not be notified of the label unless they also see it mentioned in the closing comment.

> If this step (comment and close an issue) is removed, I can label and close the issues straight from the Compensation board. This should be faster and easier.

What you should do is the following:

- Wait for the vote reveal phase to complete
- label each compensation request accordingly
- close each compensation request with a comment that reads "Closing as accepted" or "Closing as rejected" as appropriate.

I realize that it requires an extra step (away from the board) to close the issue with a comment, but it really is the best thing to do so that interested parties get notified properly of the end state of the request. So: first label the issue, then type the comment and click the "Close and comment" button. 

Additionally, I see that you archived all issues immediately after closing them. I see that my instructions here didn't fully make sense, because I wrote that we should wait until the next cycle to archive them. Given that the next cycle comes almost immediately after the vote reveal phase is complete, this doesn't leave much time for the issues to sit in the `Done` column for reference. This is my bad, and I have updated the wiki to make it clear that closed issues should remain in the `Done` column until the end of the next cycle`s proposal phase, at which point they should be archived. Please review the changes at https://bisq.wiki/index.php?title=Compensation&type=revision&diff=169&oldid=167 and let me know if you have any questions.

I have also un-archived Cycle 10 issues so that they comply with the process as documented above. Please archive them accordingly at the end of the Cycle 11 proposal phase.

I have also renamed the `Accepted` label to `was:accepted` as per the documentation and have done the same with the other related labels.

@mwithm, when you have read this comment and reviewed the process changes in the documentation, please add a comment here saying you've done so and close this issue or leave it open if you have outstanding questions / feedback. Thanks.

**Comment by cbeams** [comment]
Ping @MwithM, from the comment above:

> @MwithM, when you have read this comment and reviewed the process changes in the documentation, please add a comment here saying you've done so and close this issue or leave it open if you have outstanding questions / feedback. Thanks.

**Comment by MwithM** [comment]
@cbeams It's done, I just didn't know how to send a message to bisq DAO. Steve told me the address for it, I'm changing that for wiki compensation.
https://github.com/orgs/bisq-network/projects/5

It seems I can't close issues here, please proceed to do so.

**Comment by cbeams** [comment]
Closing as complete. Thanks @MwithM!
