### ISSUE TITLE
Evaluate current account signing flow for new user

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/admin#57]
- [x] screenshot all steps
- [x] make suggestions for improvements in https://github.com/bisq-network/projects/issues/10

Part of bisq-network/projects#10

**Comment by ripcurlx** [comment]
![Bildschirmfoto 2020-02-21 um 16 36 19](https://user-images.githubusercontent.com/170962/75363822-f4a77d00-58ba-11ea-9311-22a8e37b8751.png)
**Note:** Think about offering translated summary of tac
![Bildschirmfoto 2020-02-21 um 16 37 53](https://user-images.githubusercontent.com/170962/75363828-f7a26d80-58ba-11ea-9972-db60b91dd529.png)
![Bildschirmfoto 2020-02-21 um 16 39 14](https://user-images.githubusercontent.com/170962/75363830-f83b0400-58ba-11ea-9589-b34731db0c1d.png)
**Note:** Only show `New` badge if there is an account available where you actually need account signing.

![Bildschirmfoto 2020-02-26 um 17 21 54](https://user-images.githubusercontent.com/170962/75366068-76e57080-58be-11ea-9e82-3dee22d4eeab.png)
**Note:** If a new user opens a offer book with payment methods visible that need account signing we should present him with an additional popup or popover at the account signing column showing a visual explanation on account signing

![Bildschirmfoto 2020-02-26 um 17 22 20](https://user-images.githubusercontent.com/170962/75366078-79e06100-58be-11ea-86e3-3afa9564c886.png)

![Bildschirmfoto 2020-02-26 um 17 22 29](https://user-images.githubusercontent.com/170962/75366083-7a78f780-58be-11ea-988d-80f8d25efbbb.png)

![Bildschirmfoto 2020-02-26 um 17 23 44](https://user-images.githubusercontent.com/170962/75366088-7b118e00-58be-11ea-8b94-30963a8bb384.png)

**Note:**  Let's make this more visual (using account signing icons) and make links clickable. No-one will type links into the browser manually. 

![Bildschirmfoto 2020-02-26 um 17 24 46](https://user-images.githubusercontent.com/170962/75366090-7baa2480-58be-11ea-8604-f5405e2f7f56.png)

**Note:** No congratulations screen, no next steps. I think we should congratulate the user for creating an account and offer him buttons to e.g. in case of an SEPA(EUR) account to `Buy BTC with EUR` and `Sell BTC for EUR`. 

![Bildschirmfoto 2020-02-26 um 17 25 04](https://user-images.githubusercontent.com/170962/75366092-7c42bb00-58be-11ea-9b66-db9ca6b0e17e.png)

![Bildschirmfoto 2020-02-26 um 17 25 26](https://user-images.githubusercontent.com/170962/75366093-7c42bb00-58be-11ea-8cd7-cc4dd53498f0.png)
**Note:** Left column shouldn't cause truncation for one of our most important market in our source language.

![Bildschirmfoto 2020-02-26 um 17 26 01](https://user-images.githubusercontent.com/170962/75366095-7cdb5180-58be-11ea-9d1d-cbaf1c72e961.png)

**Note:** We removed the rounding popup to reduce the amount of popups, but now for new users we should display the popover at least once for the rounded fiat amount if seen for the first time.

![Bildschirmfoto 2020-02-26 um 17 26 56](https://user-images.githubusercontent.com/170962/75366097-7cdb5180-58be-11ea-85d3-cb06fc61c5be.png)

**Note:** Let's give this screen some visual love.

![Bildschirmfoto 2020-02-26 um 17 27 50](https://user-images.githubusercontent.com/170962/75366100-7d73e800-58be-11ea-875f-9de3e1bf62f2.png)

![Bildschirmfoto 2020-02-26 um 17 29 41](https://user-images.githubusercontent.com/170962/75366103-7d73e800-58be-11ea-8cc2-536792f797bf.png)

**Note:** Here again: No truncation should take place in one of our major markets  in the source language.

![Bildschirmfoto 2020-02-26 um 17 29 52](https://user-images.githubusercontent.com/170962/75366105-7e0c7e80-58be-11ea-9b5f-212f52522c88.png)

![Bildschirmfoto 2020-02-26 um 17 30 05](https://user-images.githubusercontent.com/170962/75366107-7e0c7e80-58be-11ea-95ff-8076c17f1db8.png)

![Bildschirmfoto 2020-02-26 um 17 30 14](https://user-images.githubusercontent.com/170962/75366108-7ea51500-58be-11ea-9659-e3929a5cc250.png)

**Note:** The trade account details should also get some visual love. Atm it is kind of hidden in this bunch of text.

![Bildschirmfoto 2020-02-26 um 17 31 31](https://user-images.githubusercontent.com/170962/75366110-7ea51500-58be-11ea-8ba2-aa78fe76a477.png)

![Bildschirmfoto 2020-02-26 um 17 31 47](https://user-images.githubusercontent.com/170962/75366111-7f3dab80-58be-11ea-8342-f0e550ff9718.png)

![Bildschirmfoto 2020-02-26 um 17 32 43](https://user-images.githubusercontent.com/170962/75366114-7f3dab80-58be-11ea-9ab6-4deb2c5c65d5.png)

**Note:** First why is the Need help? description text in the blurred background truncated in that state. Second when the user clicks `Get support` we should provide here the option to open the trade chat and `Open support ticket` should be a secondary option.

![Bildschirmfoto 2020-02-26 um 17 34 20](https://user-images.githubusercontent.com/170962/75366116-7fd64200-58be-11ea-88b3-b461f310c712.png)

**Note:** Here again. This should be a moment of joy. Congratulate the user and make the link clickable.

![Bildschirmfoto 2020-02-26 um 17 34 44](https://user-images.githubusercontent.com/170962/75366119-7fd64200-58be-11ea-94a0-5c2761015bdf.png)

![Bildschirmfoto 2020-02-26 um 17 35 05](https://user-images.githubusercontent.com/170962/75366122-7fd64200-58be-11ea-8a75-643687641eff.png)
![Bildschirmfoto 2020-02-26 um 17 35 12](https://user-images.githubusercontent.com/170962/75366123-806ed880-58be-11ea-8bba-6800014ba1fc.png)

**Comment by ripcurlx** [comment]
@cbeams @m52go While going through the first time trade process to find out issues with the account signing communication I found some other points which can be fixed with reasonable effort as well. Would be great if you could give some quick feedback on my notes. As this issue and the linked project is about account signing I'll branch out the findings into a new project afterwards.

**Comment by cbeams** [comment]
The notes make sense to me, @ripcurlx. I don't have further feedback.
