### ISSUE TITLE
Design structure and content of support case issues

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#7]
Including how to title issues, how and when to use Keybase encryption for sensitive user information, and the design of the support case issue template. Most of this was done in collaboration with @Bisq-knight.

- [ ] @bisq_knight to refine issue template to match where we ended up in the chat (or to provide further feedback about it)
- [ ] @cbeams to review

**Comment by Bisq-knight** [comment]
Did you get to try your parser on the template? And plus the comments from KB

**Comment by cbeams** [comment]
Closing this task as dropped along with its parent project at https://github.com/bisq-network/projects/issues/5.
