### ISSUE TITLE
Document the refund process

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#70]
Per https://github.com/bisq-network/roles/issues/93#issuecomment-593333519:

> There is a lot of confusion about this [RefundAgent] role, and the closely-related role played by @burningman2. To my knowledge, the relationship and workflow between these roles has never been properly documented anywhere. I would like to see this clearly written down somewhere on the wiki, probably at https://bisq.wiki/Refunds (which would be a member of the [https://bisq.wiki/Category:Processes](Processes) category). This document would take an end-to-end approach to documenting the refund process, including:
> - [ ] The conditions which lead up to a refund (e.g. a dispute between Bob and Alice that is not resolved by normal mediation and gets escalated to the Refund Agent)
> - [ ] How Bob and Alice's BTC funds get paid out to the Bisq donation address
> - [ ] How the Refund Agent is responsible for deciding what the payout distribution should actually be according to the facts and circumstances of the case, and how this is essentially the equivalent of old-style arbitration.
> - [ ] How, upon deciding that distribution, the Refund Agent pays the according amounts of BTC to Bob and Alice out of his/her own pocket, with the expectation of reimbursement in BSQ at the end of the current cycle
> - [ ] How the refund agent issues a reimbursement request for an amount of BSQ equivalent to the amount of BTC paid out of pocket to settle disputes as described above
> - [ ] How the DAO issues that BSQ
> - [ ] How the Refund Agent creates offers to buy BTC with that newly issued BSQ
> - [ ] How the donation address owner (@burningman2) takes those offers using BTC funds from the donation address
> - [ ] How the donation address owner then burns the newly-bought BSQ.
> - [ ] Why it is important from decentralization and trust-minimization perspectives that these two roles are and remain separate

**Comment by burningman2** [comment]
I can write up something. Not sure if its well enough written but content-wise I can provide the basics.

**Comment by burningman2** [comment]
I am a bit sick atm so not sure when I can start writing up something.

**Comment by m52go** [comment]
Refund process is documented at the following links:

Process - https://bisq.wiki/Arbitration
Role - https://bisq.wiki/Arbitrator
Role - https://bisq.wiki/Donation_Address_Holder

**Comment by kemccall** [comment]
Let me know if you need any priority work done.

**Comment by cbeams** [comment]
Closing as complete per @m52go's work mentioned at https://github.com/bisq-network/admin/issues/70#issuecomment-607890856.

**Comment by m52go** [comment]
Since it's related, just want to note that the manual user-driven refund process is [documented here](https://bisq.wiki/Making_a_reimbursement_request) (as requested [here](https://github.com/bisq-network/admin/issues/80#issue-619524283)). 

I don't think I communicated that to anyone (aside from RefundAgent, at the time the doc was created).
