### ISSUE TITLE
Deliver Bisq Q2 2020 Update

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#81]
Similar in form to the Bisq Q1 2020 Update call we did at #5. I'll use this issue to capture references to topics issues, proposals, projects, etc that we may want to highlight in the call.

The call will be held on Friday, June 19th from 6–7p CET, and is already in the https://bisq.network/calendar.

Call will be held via Zoom, recorded and uploaded to YouTube. Deck will be published via Google Sheets, link TBD.

**Comment by cbeams** [comment]
- [x] @cbeams to deliver call
- [x] @cbeams to upload recording to keybase://team/bisq/2020-06-19%20Q2%202020%20Update
- [x] @m52go to upload to YouTube and share link as appropriate
  - [x] Include link to slides in shownotes: https://docs.google.com/presentation/d/1iTeumZKw1GrWFZv3XPnozYewVc9RDjzJWQo_73KxPI8/edit#slide=id.g89148b8621_0_20 
  - [x] Update speaker notes in title slide to include link to YouTube video (as was done [here](https://docs.google.com/presentation/d/1xSV0EUrCaT7YaCsaolPzF1Hr68i0QMA7Yb2NqbQYTUQ/edit#slide=id.g6db4639ca5_0_83))

@m52go, if you don't see any other tasks beyond the above, please close this out when your tasks are finished. Thanks!

**Comment by m52go** [comment]
Uploaded. Can be viewed at:
https://www.youtube.com/watch?v=k_QjrhU3hrc

Closing as complete.
