### ISSUE TITLE
Send communication to @bisq-network/dao re compensation request review

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#9]
Per teamleads chat.

- [x] @m52go to send message to @bisq-network/dao that Cycle 10 is coming to a close and that compensation requests should be posted by the ~8th so team leads have a chance to review.
- [x] @m52go has agreed to send regular DAO cycle phase change notifications to @bisq-network/dao (there is no tracking issue for this, @m52go will just manage doing it)
- [x] @m52go, we didn't talk about it, but along with these phase change notifications would naturally come posting the cycle summary to @bisq-network/dao, yes?

**Comment by m52go** [comment]
Made it noon on the 11th per our Keybase chat.
https://github.com/orgs/bisq-network/teams/dao/discussions/2

> we didn't talk about it, but along with these phase change notifications would naturally come posting the cycle summary to @bisq-network/dao, yes?

Sure. But shall we continue posting cycle summaries as blog posts, so they're public, and just post links to those posts on @bisq-network/dao?

**Comment by cbeams** [comment]
> shall we continue posting cycle summaries as blog posts, so they're public, and just post links to those posts on @bisq-network/dao?

I think "cross posting" from the blog to the dao team is best. A full copy/paste is preferred to just a link, as folks may at least scan the content if it shows up in their inbox, but may or may not actually click the link to read the blog. The second reason is that I'd prefer to have the record of cycle reports in GH Discussions (and written behind to the bisq-github mailing list), rather than "just" on the blog. You might be explicit in mentioning that it's a cross post and include a link to the blog when you send the message to the dao team.

On a more general note, we should  be more conservative about our use of team `@mentions`. This was my bad to begin with. When I mentioned `@bisq-network/dao` in my original issue description above, it notified everyone in the dao and auto-subscribed them to this issue. This is a nice feature when it's actually what you want to do, but in this case it was unintentional on my part. So every active contributor is getting our comments here, until we close the issue or they individually click 'unsubscribe' via email or the web ui. Sorry about that everyone!

@m52go if you're fine with the above, please close this issue. There's nothing more from my side on it. Thanks.

**Comment by m52go** [comment]
Agreed. But I can't close this issue.

**Comment by cbeams** [comment]
> I can't close this issue.

Sorry about that. You (and all @bisq-network/team-leads) can now manage issues in this repository. Closing this as complete now.
